### ISSUE TITLE
Make optional motor controller override

### ISSUE THREAD

**Issue by thenetworkgrinch** [BroncBotz3481/YAGSL-Example#152]
Sometimes teams may wish to tune their motor controllers outside of YAGSL. YAGSL currently resets all motor controllers to factory default and applies its own configs to every motor controller. This is fine in most cases, except MAXSwerve, and some teams procesees. 

I will make an config setting in `swervedrive.json` which will force motor controllers to not be reset to factory defaults and use existing configs, this is dangerous as configs can be corrupted in normal gameplay but beneficial to teams who dont want to be forced to use the JSON to configure things like inversions or PID.

**Comment by Technologyman00** [comment]
Do we want to expand this to encoders as well?

**Comment by thenetworkgrinch** [comment]
I think that we wont fix this issue and its no longer needed, closing
