### ISSUE TITLE
Fix CANCoder Synchronization

### ISSUE THREAD

**Issue by 7910f6ba7ee4** [BroncBotz3481/YAGSL-Example#48]
https://www.chiefdelphi.com/t/yet-another-generic-swerve-library-yagsl-beta/425148/159
https://www.chiefdelphi.com/t/yet-another-generic-swerve-library-yagsl-beta/425148/117
Appear to have issues with what is believed to be the cancoder sync. 

Possible causes of issues:
- `getAbsolutePosition()` not being constrained to (0, 360) because of the offset
- the `synchronizeEncoders()` is placed in the periodic `updateOdometry()` which means a lack of causality with `setReference()`. Because of the PID loop running on the motor, with the setpoint derived from the past motor measurements and a new measurement, this could cause some unexpected temporary behavior.

It also could be easier to implement a Steer and Drive Controller to wrap the absolute encoder like democat's swervelib. This would match what they do, which is known to work.

**Comment by napro1299** [comment]
I can test this with my Falcon and CANCoder swerve today.

**Comment by jasondaming** [comment]
Just got done with an event a bit ago we don't meet till Monday but that is my day to try all kinds of new stuff like this!
